config/routes.rb
Rails.application.routes.draw do
  get "search", to: "query#search"
  delete "clear_stats", to: "query#destroy_all"
  root to: "query#index"
end

app/models/query.rb
class Query
  include Mongoid::Document
  field :sentence, type: String
  field :rating, type: Integer
  validates :sentence, presence: true, uniqueness: true
  validates :rating, presence: true
  before_validation :initialize_rating, if: :new_record?

  def increase_rating
    self.update_attribute :rating, self.rating + 1 if self.persisted?
  end

  protected
  def initialize_rating
    self.rating = 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/query_controller.rb
class QueryController < ApplicationController

  def index
    @query = Query.order_by rating: 'desc', sentence: 'asc'
  end

  def search
    if params[:sentence]
      QueryRatingWorker.perform_async(params[:sentence])
      redirect_to root_path, notice: "#{params[:sentence]} searched!" and return
    else
      redirect_to root_path
    end
  end

  def destroy_all
    if Query.all.count > 0
      Query.destroy_all
      redirect_to root_path, notice: "The statistics are clear!" and return
    else
      redirect_to root_path
    end
  end

  private
  def query_params
    params.require(:query).permit(:sentence)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <%= link_to "Stats App", root_path, class: "navbar-brand" %>
    <%= form_tag search_path, id: 'search_form', method: :get, class: 'form-inline' do |f| %>
      <%= text_field_tag :sentence, params[:sentence], class: 'form-control mr-sm-2', placeholder: 'Type your question...' %>
      <%= submit_tag 'Search', id: 'search_btn', class: 'btn btn-primary my-2 my-sm-0', disabled: true %>
    <% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stats App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert alert-success" do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= msg %>
        <% end %>
      <% end %>
      <%= yield %>
      <div class="container">
        <footer class="main-footer">
          <div class="pull-left hidden-xs">
            <% if ! @query.empty? %>
              <%= button_to "Clear", clear_stats_path, method: :delete, data: { confirm: "Are you sure you wish to clear statistics?" }, class: "btn btn-danger" %>
            <% else %>
              <%= submit_tag 'Clear', id: 'clear_btn', class: 'btn btn-danger my-2 my-sm-0', disabled: true %>
            <% end %>
          </div>
        </footer>
      </div>
    </div>
  </body>
</html>
<%= javascript_include_tag 'https://getbootstrap.com/assets/js/vendor/popper.min.js' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/query/destroy.html.erb
<h1>Query#destroy</h1>
<p>Find me in app/views/query/destroy.html.erb</p>

app/views/query/index.html.erb
<div class="container">
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>Sentence</th>
	      <th>Rating</th>
	    </tr>
	  </thead>
	  <tbody>
	    <% if @query and @query.size == 0 %>
	      <tr>
	        <td colspan="2">No questions found.</td>
	      </tr>
	    <% else %>
	      <% @query.each do |query| %>
	        <tr>
	          <td><%= query.sentence %></td>
	          <td><%= query.rating %></td>
	        </tr>
	      <% end %>
	    <% end %>
	  </tbody>
	</table>
</div>